### ISSUE TITLE
挂上VPN以后，访问不了内网，设置的是智能代理

### ISSUE THREAD

**Issue by carryxiong** [hyjsos/bshl#1]
电脑有两个网卡，一个连公网，一个连的是一个局域网，当挂上VPN以后，访问不了内网服务，但是内网的ip可以ping通，端口也能通，但就是访问不了服务，设置的是智能代理。当VPN断开以后，正常访问，这是因为这个内网ip被VPN默认代理了吗？

**Comment by hyjsos** [comment]
有可能

carrywang ***@***.***> 于2021年12月3日周五 16:12写道：
